enforce min coverage on internal packages

diff --git a/.github/workflows/internal_tests.yaml b/.github/workflows/internal_tests.yaml
--- a/.github/workflows/internal_tests.yaml
+++ b/.github/workflows/internal_tests.yaml
@@ -36,6 +36,24 @@ jobs:
         run: |
           go tool cover -func=coverage.out
 
+      - name: Generate coverage report
+        run: go tool cover -html=coverage.out -o=coverage.html
+
+      - uses: actions/upload-artifact@v5
+        with:
+          name: coverage-report
+          path: coverage.html
+
+      - name: Enforce min coverage (85%)
+        run: |
+          go tool cover -func=coverage.out | tail -1 | awk '{if ($3 < 85) exit 1}'
+          if [ "$?" -ne 0 ]; then
+              # use github actions log to print message
+              echo "::error::Code coverage is below 85%"
+              exit 1
+          fi
+
+
     services:
       postgres:
         image: postgres:latest
