remove hardcoding of min coverage

diff --git a/.github/workflows/internal_tests.yaml b/.github/workflows/internal_tests.yaml
--- a/.github/workflows/internal_tests.yaml
+++ b/.github/workflows/internal_tests.yaml
@@ -12,6 +12,8 @@ jobs:
   test:
     name: Test Internal Packages
     runs-on: [self-hosted-linux-amd64-noble-edge]
+    env:
+      COVERAGE_THRESHOLD: 85
 
     steps:
       - uses: actions/checkout@v6
@@ -47,10 +49,10 @@ jobs:
           name: coverage-report
           path: coverage.html
 
-      - name: Enforce min coverage (85%)
+      - name: Enforce min coverage
         run: |
-          if ! go tool cover -func=coverage.out | tail -1 | awk '{if ($3 < 85) exit 1}'; then
-          echo "::error::Code coverage is below 85%"
+          if ! go tool cover -func=coverage.out | tail -1 | awk '{if ($3 < ENVIRON["COVERAGE_THRESHOLD"]) exit 1}'; then
+          echo "::error::Code coverage is below $COVERAGE_THRESHOLD"
           exit 1
           fi
 
